#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "FishingComponent.generated.h"

class AStarwell;
class UEconomyComponent;
class UFishDataAsset;
class UFishingComponent;

UENUM(BlueprintType)
enum class EFishingState : uint8
{
	Idle UMETA(DisplayName="Idle"),
	Casting UMETA(DisplayName="Casting"),
	FishBiting UMETA(DisplayName="Fish Biting"),
	Reeling UMETA(DisplayName="Reeling"),
	CatchComplete UMETA(DisplayName="Catch Complete"),
	CatchFailed UMETA(DisplayName="Catch Failed")
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FFishingComponentEventSignature, UFishingComponent*, FishingComponent);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FFishingFishEventSignature, UFishingComponent*, FishingComponent, UFishDataAsset*, Fish);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_FiveParams(FFishingCatchOfferedSignature, UFishingComponent*, FishingComponent, UFishDataAsset*, Fish, AStarwell*, Starwell, UEconomyComponent*, EconomyComponent, int32, EchoScalesGranted);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FFishingTensionChangedSignature, UFishingComponent*, FishingComponent, float, NewTension);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FFishingStateChangedSignature, UFishingComponent*, FishingComponent, EFishingState, NewState);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FFishingProgressChangedSignature, UFishingComponent*, FishingComponent, FName, FishId);

USTRUCT(BlueprintType)
struct FNyxFishCollectionEntry
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Fishing|Progress")
	FName FishId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Fishing|Progress", meta=(ClampMin="0", UIMin="0"))
	int32 CatchCount = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Fishing|Progress", meta=(ClampMin="0", UIMin="0"))
	int32 PerfectCatchCount = 0;
};

USTRUCT(BlueprintType)
struct FNyxFishingProgressData
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Fishing|Progress")
	TArray<FNyxFishCollectionEntry> FishCollection;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Fishing|Progress", meta=(ClampMin="0", UIMin="0"))
	int32 TotalCatches = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Fishing|Progress", meta=(ClampMin="0", UIMin="0"))
	int32 TotalPerfectCatches = 0;
};

UCLASS(ClassGroup=(Fishing), Blueprintable, meta=(BlueprintSpawnableComponent))
class NYX_API UFishingComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UFishingComponent();

	// Fish definitions this component can choose from when a cast starts.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category="Fishing|Fish")
	TArray<TObjectPtr<UFishDataAsset>> AvailableFish;

	// Seed used with CastIndex to make fish selection and bite timing reproducible.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Fishing|Determinism")
	int32 RandomSeed;

	// Number of casts started with this component. Save this with RandomSeed to resume deterministic progression.
	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, SaveGame, Category="Fishing|Determinism")
	int32 CastIndex;

	// Fish chosen for the current cast.
	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, SaveGame, Category="Fishing|State")
	TObjectPtr<UFishDataAsset> SelectedFish;

	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, SaveGame, Category="Fishing|State")
	EFishingState FishingState;

	// Basic 0-1 pressure value for future reel timing, line break, or card modifier systems.
	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, SaveGame, Category="Fishing|State", meta=(ClampMin="0.0", ClampMax="1.0", UIMin="0.0", UIMax="1.0"))
	float Tension;

	// The deterministic bite delay generated for the current cast.
	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, SaveGame, Category="Fishing|State", meta=(ClampMin="0.0", UIMin="0.0"))
	float CurrentBiteTime;

	// Durable collection progress. Runtime cast state is intentionally not stored here.
	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, SaveGame, Category="Fishing|Progress")
	FNyxFishingProgressData FishingProgress;

	// When true, CompleteCatch automatically offers the caught fish to StarwellTarget.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Fishing|Rewards")
	bool bOfferCompletedCatchesToStarwell;

	// Optional gameplay-only target that receives completed catches as offerings.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Fishing|Rewards")
	TObjectPtr<AStarwell> StarwellTarget;

	// Optional economy component that receives Echo Scales generated by the Starwell offering.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Fishing|Rewards")
	TObjectPtr<UEconomyComponent> EconomyTarget;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingComponentEventSignature OnCastStarted;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingComponentEventSignature OnCastCancelled;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingFishEventSignature OnFishBite;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingFishEventSignature OnReelStarted;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingFishEventSignature OnCatchCompleted;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingCatchOfferedSignature OnCatchOfferedToStarwell;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingFishEventSignature OnCatchFailed;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingTensionChangedSignature OnTensionChanged;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingStateChangedSignature OnFishingStateChanged;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingComponentEventSignature OnFishingSaveApplied;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingComponentEventSignature OnFishingStateRestored;

	UPROPERTY(BlueprintAssignable, Category="Fishing|Events")
	FFishingProgressChangedSignature OnFishingProgressChanged;

	UFUNCTION(BlueprintCallable, Category="Fishing")
	bool StartCast();

	UFUNCTION(BlueprintCallable, Category="Fishing")
	void CancelCast();

	UFUNCTION(BlueprintCallable, Category="Fishing")
	bool StartReel();

	UFUNCTION(BlueprintCallable, Category="Fishing")
	void CompleteCatch(bool bPerfectCatch = false);

	UFUNCTION(BlueprintCallable, Category="Fishing")
	void FailCatch();

	UFUNCTION(BlueprintCallable, Category="Fishing")
	void SetTension(float NewTension);

	UFUNCTION(BlueprintCallable, Category="Fishing|Save")
	void RestoreSavedState(const TArray<UFishDataAsset*>& RestoredAvailableFish, int32 RestoredRandomSeed, int32 RestoredCastIndex, bool bRestoredOfferCompletedCatchesToStarwell, const FNyxFishingProgressData& RestoredProgress);

	UFUNCTION(BlueprintCallable, Category="Fishing|Progress")
	void RecordCatchProgress(UFishDataAsset* Fish, bool bPerfectCatch = false);

	UFUNCTION(BlueprintPure, Category="Fishing|Progress")
	bool HasDiscoveredFish(FName FishId) const;

	UFUNCTION(BlueprintPure, Category="Fishing|Progress")
	int32 GetCatchCountForFish(FName FishId) const;

	UFUNCTION(BlueprintPure, Category="Fishing|Progress")
	int32 GetPerfectCatchCountForFish(FName FishId) const;

	UFUNCTION(BlueprintCallable, Category="Fishing|Rewards")
	void SetCatchRewardTargets(AStarwell* NewStarwellTarget, UEconomyComponent* NewEconomyTarget);

	UFUNCTION(BlueprintCallable, Category="Fishing|Rewards")
	int32 OfferFishToStarwell(UFishDataAsset* Fish);

	UFUNCTION(BlueprintPure, Category="Fishing")
	bool IsFishing() const;

protected:
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

private:
	FTimerHandle BiteTimerHandle;

	FRandomStream MakeCastRandomStream() const;
	UFishDataAsset* SelectFishForCast(FRandomStream& RandomStream) const;
	float GenerateBiteTimeForFish(const UFishDataAsset* Fish, FRandomStream& RandomStream) const;
	UEconomyComponent* ResolveEconomyTarget() const;
	void HandleFishBite();
	void ProcessCompletedCatchRewards(UFishDataAsset* CaughtFish);
	void SetFishingState(EFishingState NewState);
	void ClearBiteTimer();
	void ClearTransientRuntimeState();
	FName ResolveFishProgressId(const UFishDataAsset* Fish) const;
	FNyxFishCollectionEntry* FindMutableCollectionEntry(FName FishId);
	const FNyxFishCollectionEntry* FindCollectionEntry(FName FishId) const;
};
